image: python:latest
stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - pip install pipenv
    - pipenv install
  script:
    - pytest

heroku:
  stage: deploy
  before_script:
    - uname -a
    - git remote add heroku https://heroku:$HEROKU_TOKEN@git.heroku.com/comtoise.git
  script:
    - git push -f heroku HEAD:refs/heads/master
  only:
      - master